export {
	createItem,
	createItemByName,
	fromNotch,
	getBlocksCanDestroy,
	getBlocksCanPlaceOn,
	getCustomLore,
	getCustomName,
	getDurabilityUsed,
	getEnchants,
	getRepairCost,
	getSpawnEggMobName,
	itemsEqual,
	setBlocksCanDestroy,
	setBlocksCanPlaceOn,
	setCustomLore,
	setCustomName,
	setDurabilityUsed,
	setEnchants,
	setRepairCost,
	toNotch,
} from "./item.js";
export type {
	Enchant,
	Item,
	NotchItem,
	NotchItemBlockId,
	NotchItemPresent,
} from "./types.js";
