import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type {
	AttributeDefinition,
	BiomeDefinition,
	BlockCollisionShapes,
	BlockDefinition,
	BlockStateProperty,
	EffectDefinition,
	EnchantmentDefinition,
	EntityDefinition,
	FoodDefinition,
	ItemDefinition,
	RawRecipe,
	Registry,
	VersionInfo,
} from "./types.ts";

const DATA_DIR = join(dirname(fileURLToPath(import.meta.url)), "../data");

const loadJson = <T>(filename: string): T =>
	JSON.parse(readFileSync(join(DATA_DIR, filename), "utf8")) as T;

/**
 * Create a registry for a specific Minecraft version.
 * Loads data from src/data/ (generated by nix run .#datagen).
 */
export const createRegistry = (version: string): Registry => {
	// Load extracted data
	const blocksArray = loadJson<BlockDefinition[]>("blocks.json");
	const itemsArray = loadJson<ItemDefinition[]>("items.json");
	const entitiesArray = loadJson<EntityDefinition[]>("entities.json");
	const effectsArray = loadJson<EffectDefinition[]>("effects.json");
	const attributesArray = loadJson<AttributeDefinition[]>("attributes.json");
	const blockCollisionShapes = loadJson<BlockCollisionShapes>("blockCollisionShapes.json");

	// These aren't extracted by datagen yet — provide empty defaults
	const biomesArray: BiomeDefinition[] = [];
	const enchantmentsArray: EnchantmentDefinition[] = [];
	const foodsArray: FoodDefinition[] = [];

	// Build indexes
	const blocksById = new Map<number, BlockDefinition>();
	const blocksByName = new Map<string, BlockDefinition>();
	const blocksByStateId = new Map<number, BlockDefinition>();

	for (const block of blocksArray) {
		blocksById.set(block.id, block);
		blocksByName.set(block.name, block);
		for (let s = block.minStateId; s <= block.maxStateId; s++) {
			blocksByStateId.set(s, block);
		}
	}

	const biomesById = new Map<number, BiomeDefinition>();
	const biomesByName = new Map<string, BiomeDefinition>();
	for (const biome of biomesArray) {
		biomesById.set(biome.id, biome);
		biomesByName.set(biome.name, biome);
	}

	const itemsById = new Map<number, ItemDefinition>();
	const itemsByName = new Map<string, ItemDefinition>();
	for (const item of itemsArray) {
		itemsById.set(item.id, item);
		itemsByName.set(item.name, item);
	}

	const enchantmentsById = new Map<number, EnchantmentDefinition>();
	const enchantmentsByName = new Map<string, EnchantmentDefinition>();
	for (const ench of enchantmentsArray) {
		enchantmentsById.set(ench.id, ench);
		enchantmentsByName.set(ench.name, ench);
	}

	const foodsById = new Map<number, FoodDefinition>();
	const foodsByName = new Map<string, FoodDefinition>();
	for (const food of foodsArray) {
		foodsById.set(food.id, food);
		foodsByName.set(food.name, food);
	}

	const entitiesById = new Map<number, EntityDefinition>();
	const entitiesByName = new Map<string, EntityDefinition>();
	for (const ent of entitiesArray) {
		entitiesById.set(ent.id, ent);
		entitiesByName.set(ent.name, ent);
	}

	const effectsById = new Map<number, EffectDefinition>();
	const effectsByName = new Map<string, EffectDefinition>();
	for (const eff of effectsArray) {
		effectsById.set(eff.id, eff);
		effectsByName.set(eff.name, eff);
	}

	const attributesByName = new Map<string, AttributeDefinition>();
	for (const attr of attributesArray) {
		attributesByName.set(attr.name, attr);
	}

	// Parse version from the string
	const parts = version.split(".");
	const major = `${parts[0]}.${parts[1]}`;

	const versionInfo: VersionInfo = {
		type: "pc",
		majorVersion: major,
		minecraftVersion: version,
		version: 774, // TODO: extract from datagen
		dataVersion: 4384, // TODO: extract from datagen
	};

	// Version comparison (simple numeric comparison on dataVersion)
	const dataVersion = versionInfo.dataVersion ?? 0;
	const versionLookup: Record<string, number> = {
		"1.18": 2860, "1.19": 3105, "1.20": 3463, "1.20.4": 3700,
		"1.20.5": 3837, "1.21": 3953, "1.21.1": 3955, "1.21.11": 4384,
	};

	return {
		version: versionInfo,
		blocksById,
		blocksByName,
		blocksByStateId,
		blocksArray,
		biomesById,
		biomesByName,
		biomesArray,
		itemsById,
		itemsByName,
		itemsArray,
		enchantmentsById,
		enchantmentsByName,
		enchantmentsArray,
		foodsById,
		foodsByName,
		foodsArray,
		entitiesById,
		entitiesByName,
		entitiesArray,
		effectsById,
		effectsByName,
		effectsArray,
		attributesByName,
		attributesArray,
		blockCollisionShapes,
		materials: {} as Readonly<Record<string, Readonly<Record<number, number>>>>,
		recipes: {} as Readonly<Record<number, readonly RawRecipe[]>>,
		language: {},
		isNewerOrEqualTo: (v: string) => dataVersion >= (versionLookup[v] ?? 0),
		isOlderThan: (v: string) => dataVersion < (versionLookup[v] ?? Infinity),
		supportFeature: (_f: string) => false,
	};
};
